const keys = [
  'title','subtitle','testNotice','localOnly','step1','backupLabel','backupHelp',
  'passwordLabel','read','step2','profileLabel','deletedData','subscription',
  'confirm','erase','reset','remainingTitle','remainingData','manageSubscription',
  'helpTitle','helpInfo','support','privacyInfo','language','ready','busyRead',
  'busyDelete','success','retry','invalid','noProfile','unavailable','wrongProof',
  'unsupportedAccount','frameBlocked',
];
const values = {
  tr: [
    "Sıralama hesabını sil",
    "Uygulamayı yeniden yüklemeden, şifreli yedeğinle hesabının silinmesini isteyebilirsin.",
    "Bu sayfa şu an yalnız test sıralama profillerini siler. Normal uygulamada sıralama henüz açık değildir.",
    "Yedek ve şifresi yalnız tarayıcıda açılır. Dosyan, şifren ve GPS verilerin sunucuya gönderilmez.",
    "1. Yedeğindeki profili doğrula","Şifreli Routelog yedeği",
    "Sıralama profiline katıldıktan sonra alınmış bir yedek seç. En fazla 50 MB.",
    "Yedek şifresi","Yedeği bu cihazda aç","2. Silmeyi onayla","Profil kimliği",
    "Sıralama adı, puanlar, katkılar, sezon katılımı, kurtarma bilgisi ve bağlı anonim Supabase hesabı silinir.",
    "Telefondaki kişisel aktivitelerin ve rotaların bu sayfayla silinmez. Mağaza aboneliğin iptal edilmez.",
    "Bu profili kalıcı olarak silmek istiyorum. Eski yedeklerle geri getirilemeyeceğini anladım.",
    "Sıralama hesabını kalıcı sil","Seçimi temizle","Silme sonrası kalan kayıtlar",
    "Eski yedekle yeniden oluşturmayı önlemek için ad ve Auth sahibi içermeyen minimal profil kimliği/silme anı kaydı kalır. Teknik servis kayıtları, RevenueCat müşteri verisi ve mağaza kayıtlarının temizliği ayrı süreçtir; bu test işlemi bunları silmez.",
    "Google Play aboneliklerini yönet","Yedeğine erişemiyor musun?",
    "Silme talebin için destekle iletişime geçebilirsin. Yalnız kullanıcı adı sahiplik kanıtı değildir. Yedeğini, şifreni veya kurtarma kodunu e-postayla gönderme; talep güvenli sahiplik doğrulamasından sonra işlenir.",
    "Hesap silme talebi için destek",
    "Sayfa çerez, analiz veya kalıcı tarayıcı depolaması kullanmaz. Yalnız silmeyi onaylayınca profil kimliği ve kurtarma kanıtı test sunucusuna gönderilir.",
    "Dil","Profil doğrulandı. Kimliği kontrol et ve silmek istiyorsan onayla.","Yedek bu cihazda açılıyor…",
    "Silme sonucu bekleniyor…","Sıralama hesabı silindi. Eski yedek bu profili geri getiremez.",
    "Silme sonucu doğrulanamadı. Profil bilgisi bu açık sayfada korunuyor; tekrar silmeyi deneyebilirsin. Yedek dosyanı sakla.",
    "Yedek açılamadı. Şifre yanlış, dosya bozuk, desteklenmeyen bir sürümde veya 50 MB'den büyük olabilir.",
    "Bu yedekte geçerli bir sıralama profili yok. Katılımdan sonra alınmış yedeğini seç.",
    "Güvenli yerel şifre çözme kullanılamıyor. Bu HTTPS sayfasını güncel bir tarayıcıyla aç.",
    "Profil kanıtı doğrulanamadı. Doğru yedeği seç veya destekle iletişime geç.",
    "Bu hesap türü burada silinemiyor. Destekle iletişime geç.",
    "Silme işlemi gömülü bir çerçevede kullanılamaz. Bu sayfayı doğrudan aç.",
  ],
  en: [
    "Delete your ranking account","Request deletion with your encrypted backup, without reinstalling the app.",
    "This page currently deletes test ranking profiles only. Rankings are not yet enabled in the regular app.",
    "Your backup is decrypted only in this browser. The file, password and GPS data are never uploaded.",
    "1. Verify the profile in your backup","Encrypted Routelog backup",
    "Choose a backup made after joining the ranking. Maximum 50 MB.",
    "Backup password","Open backup on this device","2. Confirm deletion","Profile ID",
    "Your ranking name, scores, contributions, season membership, recovery information and linked anonymous Supabase account are deleted.",
    "This page does not delete personal activities or routes on your phone. Your store subscription is not cancelled.",
    "I want to permanently delete this profile. I understand that old backups cannot recover it.",
    "Permanently delete ranking account","Clear selection","Records remaining after deletion",
    "A minimal profile ID/deletion-time record, without a name or Auth owner, prevents resurrection from old backups. Technical service logs, RevenueCat customer data and store records have separate cleanup processes; this test operation does not delete them.",
    "Manage Google Play subscriptions","Cannot access your backup?",
    "Contact support to request deletion. A username alone is not proof of ownership. Do not email your backup, password or recovery code; requests are processed after secure ownership verification.",
    "Support for account deletion",
    "This page uses no cookies, analytics or persistent browser storage. Only after confirmation are the profile ID and recovery proof sent to the test server.",
    "Language","Profile verified. Check its ID and confirm if you want to delete it.","Opening backup on this device…",
    "Waiting for deletion result…","Ranking account deleted. Old backups cannot recover this profile.",
    "Deletion could not be confirmed. The profile remains in this open page so you can retry. Keep your backup file.",
    "Could not open the backup. The password may be wrong, or the file damaged, unsupported or larger than 50 MB.",
    "No valid ranking profile in this backup. Choose one made after joining.",
    "Secure local decryption is unavailable. Open this HTTPS page in an up-to-date browser.",
    "Profile proof could not be verified. Choose the correct backup or contact support.",
    "This account type cannot be deleted here. Contact support.",
    "Deletion is unavailable inside an embedded frame. Open this page directly.",
  ],
  de: [
    "Ranglistenkonto löschen","Beantrage die Löschung mit deinem verschlüsselten Backup, ohne die App neu zu installieren.",
    "Diese Seite löscht derzeit nur Testprofile. Ranglisten sind in der regulären App noch nicht verfügbar.",
    "Das Backup wird nur im Browser entschlüsselt. Datei, Passwort und GPS-Daten werden nicht hochgeladen.",
    "1. Profil im Backup prüfen","Verschlüsseltes Routelog-Backup","Wähle ein Backup nach der Ranglistenteilnahme. Maximal 50 MB.",
    "Backup-Passwort","Backup auf diesem Gerät öffnen","2. Löschung bestätigen","Profil-ID",
    "Ranglistenname, Punkte, Beiträge, Saisonmitgliedschaft, Wiederherstellungsdaten und das verknüpfte anonyme Supabase-Konto werden gelöscht.",
    "Persönliche Aktivitäten und Routen auf dem Telefon werden nicht gelöscht. Dein Store-Abo wird nicht gekündigt.",
    "Ich möchte dieses Profil endgültig löschen. Alte Backups können es nicht wiederherstellen.",
    "Ranglistenkonto endgültig löschen","Auswahl löschen","Verbleibende Daten",
    "Ein minimaler Eintrag mit Profil-ID/Löschzeit ohne Name oder Auth-Inhaber verhindert Wiederherstellung aus alten Backups. Technische Logs, RevenueCat-Kundendaten und Store-Daten haben eigene Löschprozesse; dieser Test löscht sie nicht.",
    "Google-Play-Abos verwalten","Kein Zugriff auf dein Backup?",
    "Kontaktiere den Support für einen Löschantrag. Ein Benutzername allein beweist keine Inhaberschaft. Sende kein Backup, Passwort oder Wiederherstellungscode per E-Mail. Die Bearbeitung erfolgt nach sicherer Prüfung.",
    "Support für Kontolöschung",
    "Keine Cookies, Analyse oder dauerhafte Browserspeicherung. Erst nach Bestätigung werden Profil-ID und Wiederherstellungsnachweis an den Testserver gesendet.",
    "Sprache","Profil geprüft. Prüfe die ID und bestätige die gewünschte Löschung.","Backup wird lokal geöffnet…",
    "Löschbestätigung wird erwartet…","Ranglistenkonto gelöscht. Alte Backups können das Profil nicht wiederherstellen.",
    "Löschung nicht bestätigt. Das Profil bleibt in dieser offenen Seite für einen erneuten Versuch. Bewahre das Backup auf.",
    "Backup konnte nicht geöffnet werden. Passwort falsch, Datei beschädigt, nicht unterstützt oder über 50 MB.",
    "Kein gültiges Ranglistenprofil im Backup. Wähle ein Backup nach der Teilnahme.",
    "Sichere lokale Entschlüsselung nicht verfügbar. Öffne diese HTTPS-Seite in einem aktuellen Browser.",
    "Profilnachweis nicht bestätigt. Wähle das richtige Backup oder kontaktiere den Support.",
    "Dieser Kontotyp kann hier nicht gelöscht werden. Kontaktiere den Support.",
    "Löschung in einem eingebetteten Frame nicht verfügbar. Öffne diese Seite direkt.",
  ],
  es: [
    "Eliminar cuenta de clasificación","Solicita la eliminación con tu copia cifrada, sin reinstalar la app.",
    "Esta página solo elimina perfiles de prueba. La clasificación aún no está disponible en la app normal.",
    "La copia se descifra solo en este navegador. No se envían el archivo, la contraseña ni los datos GPS.",
    "1. Verifica el perfil de tu copia","Copia cifrada de Routelog","Elige una copia posterior a la inscripción. Máximo 50 MB.",
    "Contraseña de la copia","Abrir copia en este dispositivo","2. Confirma la eliminación","ID del perfil",
    "Se eliminan el nombre, los puntos, las contribuciones, la participación de temporada, la recuperación y la cuenta anónima de Supabase vinculada.",
    "Esta página no elimina actividades o rutas del teléfono. No cancela tu suscripción de la tienda.",
    "Quiero eliminar este perfil definitivamente. Entiendo que las copias antiguas no podrán recuperarlo.",
    "Eliminar cuenta definitivamente","Limpiar selección","Datos que permanecen",
    "Un registro mínimo de ID/fecha de eliminación, sin nombre ni titular de Auth, impide restaurar el perfil. Los registros técnicos, datos de cliente de RevenueCat y datos de la tienda tienen procesos separados; esta prueba no los elimina.",
    "Gestionar suscripciones de Google Play","¿No puedes acceder a la copia?",
    "Contacta con soporte para solicitar la eliminación. El nombre no demuestra titularidad. No envíes tu copia, contraseña ni código por correo; la solicitud se procesa tras una verificación segura.",
    "Soporte para eliminar la cuenta",
    "Sin cookies, analítica ni almacenamiento persistente. Solo tras confirmar se envían el ID y la prueba de recuperación al servidor de prueba.",
    "Idioma","Perfil verificado. Revisa su ID y confirma si deseas eliminarlo.","Abriendo copia en este dispositivo…",
    "Esperando el resultado…","Cuenta eliminada. Las copias antiguas no recuperarán el perfil.",
    "No se pudo confirmar. El perfil se mantiene en esta página abierta para reintentar. Conserva tu copia.",
    "No se pudo abrir. Contraseña incorrecta, archivo dañado, no compatible o mayor de 50 MB.",
    "La copia no contiene un perfil válido. Elige una copia posterior a la inscripción.",
    "Descifrado local seguro no disponible. Abre esta página HTTPS en un navegador actualizado.",
    "No se pudo verificar la prueba. Elige la copia correcta o contacta con soporte.",
    "No se puede eliminar este tipo de cuenta aquí. Contacta con soporte.",
    "No se puede eliminar desde un marco integrado. Abre la página directamente.",
  ],
  fr: [
    "Supprimer le compte de classement","Demande la suppression avec ta sauvegarde chiffrée, sans réinstaller l’application.",
    "Cette page supprime seulement les profils de test. Le classement n’est pas encore disponible dans l’application normale.",
    "La sauvegarde est déchiffrée uniquement dans ce navigateur. Fichier, mot de passe et GPS ne sont pas envoyés.",
    "1. Vérifier le profil sauvegardé","Sauvegarde Routelog chiffrée","Choisis une sauvegarde créée après l’inscription. Maximum 50 Mo.",
    "Mot de passe de sauvegarde","Ouvrir sur cet appareil","2. Confirmer la suppression","Identifiant du profil",
    "Nom, scores, contributions, participation à la saison, récupération et compte Supabase anonyme associé sont supprimés.",
    "Cette page ne supprime pas les activités et parcours du téléphone. L’abonnement de la boutique n’est pas annulé.",
    "Je veux supprimer définitivement ce profil. Les anciennes sauvegardes ne pourront pas le récupérer.",
    "Supprimer définitivement","Effacer la sélection","Données conservées",
    "Un enregistrement minimal identifiant/date de suppression, sans nom ni propriétaire Auth, empêche la restauration. Les journaux techniques, données client RevenueCat et données de boutique ont des processus distincts ; ce test ne les supprime pas.",
    "Gérer les abonnements Google Play","Sauvegarde inaccessible ?",
    "Contacte le support pour demander la suppression. Le nom seul ne prouve pas la propriété. N’envoie pas sauvegarde, mot de passe ou code par e-mail ; une vérification sécurisée est nécessaire.",
    "Support pour la suppression du compte",
    "Aucun cookie, analyse ou stockage persistant. L’identifiant et la preuve de récupération sont envoyés au serveur de test seulement après confirmation.",
    "Langue","Profil vérifié. Vérifie l’identifiant et confirme la suppression souhaitée.","Ouverture locale de la sauvegarde…",
    "En attente du résultat…","Compte supprimé. Les anciennes sauvegardes ne pourront pas récupérer ce profil.",
    "Suppression non confirmée. Le profil reste dans cette page ouverte pour réessayer. Conserve ta sauvegarde.",
    "Impossible d’ouvrir : mot de passe incorrect, fichier endommagé, non pris en charge ou supérieur à 50 Mo.",
    "Aucun profil valide dans cette sauvegarde. Choisis une sauvegarde après inscription.",
    "Déchiffrement local sécurisé indisponible. Ouvre cette page HTTPS dans un navigateur à jour.",
    "Preuve non vérifiée. Choisis la bonne sauvegarde ou contacte le support.",
    "Ce type de compte ne peut pas être supprimé ici. Contacte le support.",
    "Suppression indisponible dans un cadre intégré. Ouvre cette page directement.",
  ],
  it: [
    "Elimina l’account della classifica","Richiedi l’eliminazione con il backup cifrato, senza reinstallare l’app.",
    "Questa pagina elimina solo profili di test. La classifica non è ancora disponibile nell’app normale.",
    "Il backup viene decifrato solo nel browser. File, password e GPS non vengono caricati.",
    "1. Verifica il profilo nel backup","Backup Routelog cifrato","Scegli un backup successivo all’iscrizione. Massimo 50 MB.",
    "Password del backup","Apri backup su questo dispositivo","2. Conferma l’eliminazione","ID profilo",
    "Nome, punteggi, contributi, iscrizione stagionale, recupero e account Supabase anonimo collegato vengono eliminati.",
    "Questa pagina non elimina attività e percorsi dal telefono. Non annulla l’abbonamento dello store.",
    "Voglio eliminare definitivamente questo profilo. I vecchi backup non potranno recuperarlo.",
    "Elimina definitivamente","Cancella selezione","Dati conservati",
    "Un record minimo ID/data di eliminazione, senza nome o proprietario Auth, impedisce il ripristino. Log tecnici, dati cliente RevenueCat e dello store hanno processi separati; questo test non li elimina.",
    "Gestisci abbonamenti Google Play","Non riesci ad accedere al backup?",
    "Contatta l’assistenza per la richiesta. Il nome non dimostra la proprietà. Non inviare backup, password o codice via e-mail; la richiesta viene elaborata dopo una verifica sicura.",
    "Assistenza per eliminare l’account",
    "Niente cookie, analisi o archiviazione persistente. ID e prova di recupero vengono inviati al server di test solo dopo la conferma.",
    "Lingua","Profilo verificato. Controlla l’ID e conferma se vuoi eliminarlo.","Apertura locale del backup…",
    "In attesa del risultato…","Account eliminato. I vecchi backup non recupereranno il profilo.",
    "Eliminazione non confermata. Il profilo resta nella pagina aperta per riprovare. Conserva il backup.",
    "Impossibile aprire: password errata, file danneggiato, non supportato o superiore a 50 MB.",
    "Nessun profilo valido nel backup. Scegline uno successivo all’iscrizione.",
    "Decifratura locale sicura non disponibile. Apri questa pagina HTTPS in un browser aggiornato.",
    "Prova non verificata. Scegli il backup corretto o contatta l’assistenza.",
    "Questo tipo di account non può essere eliminato qui. Contatta l’assistenza.",
    "Eliminazione non disponibile in un frame incorporato. Apri direttamente la pagina.",
  ],
  pt: [
    "Excluir conta do ranking","Solicite a exclusão com seu backup criptografado, sem reinstalar o app.",
    "Esta página exclui apenas perfis de teste. O ranking ainda não está disponível no app normal.",
    "O backup é descriptografado apenas no navegador. Arquivo, senha e GPS não são enviados.",
    "1. Verifique o perfil do backup","Backup criptografado do Routelog","Escolha um backup feito após participar do ranking. Máximo 50 MB.",
    "Senha do backup","Abrir backup neste dispositivo","2. Confirme a exclusão","ID do perfil",
    "Nome, pontos, contribuições, participação na temporada, recuperação e conta anônima do Supabase vinculada são excluídos.",
    "Esta página não exclui atividades ou rotas do telefone. Sua assinatura da loja não é cancelada.",
    "Quero excluir este perfil permanentemente. Entendo que backups antigos não poderão recuperá-lo.",
    "Excluir conta permanentemente","Limpar seleção","Dados que permanecem",
    "Um registro mínimo de ID/data de exclusão, sem nome nem titular Auth, impede a restauração. Logs técnicos, dados de cliente RevenueCat e da loja têm processos separados; este teste não os exclui.",
    "Gerenciar assinaturas Google Play","Não consegue acessar o backup?",
    "Contate o suporte para solicitar a exclusão. O nome sozinho não comprova titularidade. Não envie backup, senha ou código por e-mail; a solicitação é processada após verificação segura.",
    "Suporte para excluir a conta",
    "Sem cookies, análises ou armazenamento persistente. ID e prova de recuperação são enviados ao servidor de teste só após confirmação.",
    "Idioma","Perfil verificado. Confira o ID e confirme se deseja excluí-lo.","Abrindo backup localmente…",
    "Aguardando o resultado…","Conta excluída. Backups antigos não recuperarão o perfil.",
    "Exclusão não confirmada. O perfil fica nesta página aberta para tentar novamente. Guarde seu backup.",
    "Não foi possível abrir: senha incorreta, arquivo danificado, não suportado ou maior que 50 MB.",
    "Nenhum perfil válido neste backup. Escolha um backup feito após participar.",
    "Descriptografia local segura indisponível. Abra esta página HTTPS num navegador atualizado.",
    "Prova não verificada. Escolha o backup correto ou contate o suporte.",
    "Este tipo de conta não pode ser excluído aqui. Contate o suporte.",
    "Exclusão indisponível em um quadro incorporado. Abra a página diretamente.",
  ],
  ru: [
    "Удалить аккаунт рейтинга","Запроси удаление с помощью зашифрованной копии без переустановки приложения.",
    "Эта страница удаляет только тестовые профили. В обычном приложении рейтинг пока недоступен.",
    "Копия расшифровывается только в браузере. Файл, пароль и GPS не отправляются на сервер.",
    "1. Проверь профиль в копии","Зашифрованная копия Routelog","Выбери копию после вступления в рейтинг. Не более 50 МБ.",
    "Пароль копии","Открыть копию на этом устройстве","2. Подтверди удаление","ID профиля",
    "Удаляются имя, баллы, вклады, участие в сезоне, данные восстановления и связанный анонимный аккаунт Supabase.",
    "Активности и маршруты на телефоне не удаляются. Подписка магазина не отменяется.",
    "Хочу навсегда удалить этот профиль. Старые копии не смогут его восстановить.",
    "Удалить аккаунт навсегда","Очистить выбор","Оставшиеся данные",
    "Минимальная запись ID/времени удаления без имени и владельца Auth защищает от восстановления. Технические журналы, данные клиента RevenueCat и магазина очищаются отдельно; этот тест их не удаляет.",
    "Управлять подписками Google Play","Нет доступа к копии?",
    "Обратись в поддержку для запроса удаления. Имя не доказывает владение. Не отправляй копию, пароль или код по почте; нужна безопасная проверка владения.",
    "Поддержка по удалению аккаунта",
    "Без cookies, аналитики и постоянного хранения в браузере. ID и доказательство восстановления отправляются тестовому серверу только после подтверждения.",
    "Язык","Профиль проверен. Проверь ID и подтверди желаемое удаление.","Локальное открытие копии…",
    "Ожидание результата…","Аккаунт удалён. Старые копии не восстановят профиль.",
    "Удаление не подтверждено. Профиль остаётся на открытой странице для повтора. Сохрани копию.",
    "Не удалось открыть: неверный пароль, повреждённый, неподдерживаемый файл или размер более 50 МБ.",
    "В копии нет действительного профиля. Выбери копию после вступления.",
    "Безопасная локальная расшифровка недоступна. Открой HTTPS-страницу в актуальном браузере.",
    "Доказательство не подтверждено. Выбери правильную копию или обратись в поддержку.",
    "Этот тип аккаунта нельзя удалить здесь. Обратись в поддержку.",
    "Удаление недоступно во встроенном фрейме. Открой страницу напрямую.",
  ],
  ar: [
    "حذف حساب الترتيب","اطلب الحذف باستخدام نسختك المشفرة دون إعادة تثبيت التطبيق.",
    "تحذف هذه الصفحة ملفات الترتيب التجريبية فقط. الترتيب غير متاح بعد في التطبيق العادي.",
    "يتم فك النسخة داخل المتصفح فقط. لا يُرفع الملف أو كلمة المرور أو بيانات GPS.",
    "1. تحقق من الملف في النسخة","نسخة Routelog المشفرة","اختر نسخة أُنشئت بعد الانضمام إلى الترتيب. الحد الأقصى 50 MB.",
    "كلمة مرور النسخة","فتح النسخة على هذا الجهاز","2. تأكيد الحذف","معرّف الملف",
    "يُحذف الاسم والنقاط والمساهمات وعضوية الموسم ومعلومات الاسترداد وحساب Supabase المجهول المرتبط.",
    "لا تُحذف أنشطتك ومساراتك على الهاتف بهذه الصفحة. لا يُلغى اشتراك المتجر.",
    "أريد حذف هذا الملف نهائياً. أفهم أن النسخ القديمة لن تستعيده.",
    "حذف الحساب نهائياً","مسح الاختيار","البيانات المتبقية",
    "يبقى سجل مختصر للمعرّف ووقت الحذف دون اسم أو مالك Auth لمنع الاستعادة. للسجلات التقنية وبيانات عميل RevenueCat والمتجر إجراءات منفصلة؛ لا يحذفها هذا الاختبار.",
    "إدارة اشتراكات Google Play","لا يمكنك الوصول إلى النسخة؟",
    "تواصل مع الدعم لطلب الحذف. الاسم وحده لا يثبت الملكية. لا ترسل النسخة أو كلمة المرور أو رمز الاسترداد بالبريد؛ يُعالج الطلب بعد تحقق آمن.",
    "الدعم لطلب حذف الحساب",
    "لا ملفات تعريف ارتباط أو تحليلات أو تخزين دائم بالمتصفح. يُرسل المعرّف ودليل الاسترداد إلى الخادم التجريبي بعد التأكيد فقط.",
    "اللغة","تم التحقق. راجع المعرّف وأكد إن أردت الحذف.","جارٍ فتح النسخة محلياً…",
    "في انتظار نتيجة الحذف…","تم حذف الحساب. لن تستعيد النسخ القديمة هذا الملف.",
    "لم يتأكد الحذف. يبقى الملف في الصفحة المفتوحة لإعادة المحاولة. احتفظ بنسختك.",
    "تعذر الفتح. كلمة مرور خاطئة أو ملف تالف أو غير مدعوم أو أكبر من 50 MB.",
    "لا يوجد ملف ترتيب صالح في النسخة. اختر نسخة بعد الانضمام.",
    "فك التشفير المحلي الآمن غير متاح. افتح صفحة HTTPS بمتصفح حديث.",
    "تعذر التحقق من الدليل. اختر النسخة الصحيحة أو تواصل مع الدعم.",
    "لا يمكن حذف هذا النوع من الحسابات هنا. تواصل مع الدعم.",
    "الحذف غير متاح داخل إطار مضمن. افتح الصفحة مباشرة.",
  ],
  ja: [
    "ランキングアカウントを削除","アプリを再インストールせず、暗号化バックアップで削除を申請できます。",
    "このページはテスト用プロフィールのみを削除します。通常版ではランキングはまだ利用できません。",
    "バックアップはブラウザー内だけで復号します。ファイル、パスワード、GPSデータは送信しません。",
    "1. バックアップのプロフィールを確認","暗号化されたRoutelogバックアップ","ランキング参加後に作成したバックアップを選択してください。最大50 MB。",
    "バックアップのパスワード","この端末でバックアップを開く","2. 削除を確認","プロフィールID",
    "名前、スコア、貢献記録、シーズン参加、復旧情報、関連する匿名Supabaseアカウントを削除します。",
    "端末の個人アクティビティやルートは削除しません。ストアの定期購入は解約されません。",
    "このプロフィールを完全に削除します。古いバックアップでも復旧できないことを理解しました。",
    "アカウントを完全に削除","選択をクリア","削除後に残る記録",
    "復旧を防ぐため、名前やAuth所有者を含まない最小限のIDと削除日時が残ります。技術ログ、RevenueCat顧客データ、ストア記録は別の処理が必要で、このテストでは削除しません。",
    "Google Playの定期購入を管理","バックアップにアクセスできませんか？",
    "削除申請はサポートに連絡してください。名前だけでは所有権を確認できません。バックアップ、パスワード、復旧コードをメールで送らないでください。安全な所有権確認後に処理します。",
    "アカウント削除のサポート",
    "Cookie、解析、永続的なブラウザー保存は使用しません。確認後にIDと復旧証明のみをテストサーバーに送ります。",
    "言語","プロフィールを確認しました。IDを確認し、削除する場合は同意してください。","端末内でバックアップを開いています…",
    "削除結果を待っています…","削除しました。古いバックアップでも復旧できません。",
    "削除を確認できませんでした。このページには再試行用に情報が残っています。バックアップを保管してください。",
    "開けませんでした。パスワードの誤り、破損、未対応形式、または50 MB超の可能性があります。",
    "有効なプロフィールがありません。参加後のバックアップを選択してください。",
    "安全なローカル復号が使えません。最新のブラウザーでHTTPSページを開いてください。",
    "証明を確認できません。正しいバックアップを選ぶかサポートに連絡してください。",
    "この種類のアカウントはここでは削除できません。サポートに連絡してください。",
    "埋め込みフレーム内では削除できません。このページを直接開いてください。",
  ],
  ko: [
    "순위 계정 삭제","앱을 다시 설치하지 않고 암호화 백업으로 삭제를 요청하세요.",
    "이 페이지는 테스트 프로필만 삭제합니다. 일반 앱에서는 아직 순위를 사용할 수 없습니다.",
    "백업은 브라우저 안에서만 복호화됩니다. 파일, 비밀번호, GPS 데이터는 업로드되지 않습니다.",
    "1. 백업 프로필 확인","암호화된 Routelog 백업","순위 참여 후 만든 백업을 선택하세요. 최대 50 MB.",
    "백업 비밀번호","이 기기에서 백업 열기","2. 삭제 확인","프로필 ID",
    "이름, 점수, 기여, 시즌 참여, 복구 정보, 연결된 익명 Supabase 계정이 삭제됩니다.",
    "휴대전화의 활동과 경로는 삭제되지 않습니다. 스토어 구독은 취소되지 않습니다.",
    "이 프로필을 영구 삭제하며 이전 백업으로도 복구할 수 없음을 이해했습니다.",
    "계정 영구 삭제","선택 지우기","남는 기록",
    "복구 방지를 위해 이름이나 Auth 소유자 없는 최소 ID/삭제 시각이 남습니다. 기술 로그, RevenueCat 고객 데이터 및 스토어 기록은 별도 처리이며 이 테스트는 삭제하지 않습니다.",
    "Google Play 구독 관리","백업에 접근할 수 없나요?",
    "지원에 삭제를 요청하세요. 이름만으로 소유권을 증명할 수 없습니다. 백업, 비밀번호, 복구 코드를 이메일로 보내지 마세요. 안전한 소유권 확인 후 처리됩니다.",
    "계정 삭제 지원",
    "쿠키, 분석, 영구 브라우저 저장을 사용하지 않습니다. 확인 후에만 ID와 복구 증명을 테스트 서버에 보냅니다.",
    "언어","프로필 확인 완료. ID를 확인하고 삭제하려면 동의하세요.","기기에서 백업 여는 중…",
    "삭제 결과 대기 중…","계정이 삭제되었습니다. 이전 백업으로 복구할 수 없습니다.",
    "삭제를 확인하지 못했습니다. 재시도를 위해 열린 페이지에 정보가 유지됩니다. 백업을 보관하세요.",
    "열 수 없습니다. 잘못된 비밀번호, 손상, 지원하지 않는 형식 또는 50 MB 초과일 수 있습니다.",
    "유효한 프로필이 없습니다. 참여 후 만든 백업을 선택하세요.",
    "안전한 로컬 복호화를 사용할 수 없습니다. 최신 브라우저로 HTTPS 페이지를 여세요.",
    "증명을 확인할 수 없습니다. 올바른 백업을 선택하거나 지원에 문의하세요.",
    "이 계정 유형은 여기서 삭제할 수 없습니다. 지원에 문의하세요.",
    "삽입된 프레임에서는 삭제할 수 없습니다. 페이지를 직접 여세요.",
  ],
  zh: [
    "删除排行榜账户","无需重新安装应用，可使用加密备份申请删除。",
    "此页面仅删除测试排行榜资料。正式应用尚未开放排行榜。",
    "备份仅在浏览器内解密。文件、密码和GPS数据不会上传。",
    "1. 验证备份中的资料","Routelog加密备份","请选择参加排行榜后创建的备份，最大50 MB。",
    "备份密码","在此设备打开备份","2. 确认删除","资料ID",
    "排行榜名称、分数、贡献、赛季参与、恢复信息及关联的匿名Supabase账户将被删除。",
    "此页面不会删除手机上的活动和路线，也不会取消商店订阅。",
    "我要永久删除此资料，并理解旧备份也无法恢复。",
    "永久删除账户","清除选择","删除后保留的记录",
    "为防止旧备份恢复，会保留不含名称或Auth所有者的最小ID/删除时间记录。技术日志、RevenueCat客户数据和商店记录需另行处理，此测试不删除这些数据。",
    "管理Google Play订阅","无法访问备份？",
    "请联系支持申请删除。用户名本身不证明所有权。不要通过邮件发送备份、密码或恢复码；申请将在安全验证所有权后处理。",
    "账户删除支持",
    "不使用Cookie、分析或持久浏览器存储。仅在确认后向测试服务器发送ID和恢复证明。",
    "语言","资料已验证。请核对ID，并在需要删除时确认。","正在本地打开备份…",
    "正在等待删除结果…","账户已删除。旧备份无法恢复此资料。",
    "无法确认删除。资料暂留在此打开的页面中供重试，请保管备份。",
    "无法打开。密码可能错误、文件损坏、格式不支持或超过50 MB。",
    "此备份没有有效资料，请选择参与后创建的备份。",
    "无法使用安全本地解密，请用最新浏览器打开此HTTPS页面。",
    "无法验证证明，请选择正确备份或联系支持。",
    "无法在此删除此账户类型，请联系支持。",
    "嵌入框架中无法删除，请直接打开此页面。",
  ],
};
export const languages = Object.freeze(Object.keys(values));
export const messages = Object.freeze(Object.fromEntries(Object.entries(values).map(([locale, entries]) => {
  if (entries.length !== keys.length) throw new Error('Incomplete translation: ' + locale);
  return [locale, Object.freeze(Object.fromEntries(keys.map((key, index) => [key, entries[index]])))];
})));
